---
title: "`r emo::ji('muscle')` EGİTİMDE ARAŞTIRMA YÖNTEMLERİ"
subtitle: " <br> `r emo::ji('graph')` Araştırmalarda İç Geçerlik ve Dış Geçerlik"
author: "<br> <br> `r emo::ji('woman_teacher')` Dr. Kübra ATALAY KABASAKAL <br> Hacettepe Üniversitesi"
date: "2021-2022 Bahar-Hafta 11 <br> <br> <br> <br>`r emo::ji('e-mail')` katalay@hacettepe.edu.tr"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", "slides-style.css"]
    nature:
      highlightStyle: solarized-light
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
---

```{r child = "../setup.Rmd"}
```

```{r set-theme, include=FALSE}
library(emoji)
library(xaringanthemer)
library(dplyr)

style_duo_accent(
  primary_color      = "#0F4C81", # pantone classic blue
  secondary_color    = "#B6CADA", # pantone baby blue
  header_font_google = google_font("Raleway"),
  text_font_google   = google_font("Raleway", "300", "300i"),
  code_font_google   = google_font("Source Code Pro"),
  text_font_size     = "30px"
)
```

---
## Araştırmalarda İç Geçerlik ve Dış Geçerlik .huge[`r emo::ji("stats")`]

.hand[İçerik...]

-   Veri Nedir?
-   Nicel Veri Toplama Araçları
    -   Anketler
    -   Ölçek
    -   Envanter
    -   Test
-   Çevirim için veri toplama araçları
-   **ODEV-III (++) Çevirim içi Anket Hazırlama**

